from mne-python

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,41 +1,110 @@
-dist: trusty
+language: c
+dist: xenial
 sudo: false
-
-language: python
-
 cache:
-  directories:
-  - $HOME/.cache/pip
+  apt: true
+  pip: true
+env:
+    # TRAVIS_PYTHON_VERSION is only needed for neo's setup.py
+    # OPENBLAS_NUM_THREADS=1 avoid slowdowns:
+    # https://github.com/xianyi/OpenBLAS/issues/731
+    global: PYTHON_VERSION=3.6 DISPLAY=:99.0 MNE_LOGGING_LEVEL=warning TEST_LOCATION=src
+            PIP_DEPENDENCIES="codecov nitime"
+            TRAVIS_PYTHON_VERSION=3.6 CONDA_VERSION=">=4.3.27"
+            OPENBLAS_NUM_THREADS=1
 
 matrix:
-  include:
-    - env: PYTHON_VERSION="3.5" NUMPY_VERSION="1.13.1" SCIPY_VERSION="0.19.1"
-           SKLEARN_VERSION="0.19.1"
-    - env: PYTHON_VERSION="3.6" NUMPY_VERSION="1.13.1" SCIPY_VERSION="0.19.1"
-           SKLEARN_VERSION="0.19.1"
-    - env: PYTHON_VERSION="3.7" NUMPY_VERSION="*" SCIPY_VERSION="*"
-           SKLEARN_VERSION="*"
+    include:
+        # No data + style testing
+        - os: linux
+          env: DEPS=nodata MNE_DONTWRITE_HOME=true MNE_FORCE_SERIAL=true MNE_SKIP_NETWORK_TEST=1
+               CONDA_DEPENDENCIES="numpy scipy matplotlib sphinx pytest pytest-timeout pytest-cov pytest-mock"
+               PIP_DEPENDENCIES="flake8 numpydoc codespell pydocstyle codecov check-manifest pytest-sugar pytest-faulthandler"
+
+        # Linux
+        - os: linux
+          env: CONDA_ENVIRONMENT="environment.yml"
+
+        # OSX conda
+        - os: osx
+          env: CONDA_ENVIRONMENT="environment.yml"
+
+        # PIP + non-default stim channel
+        - os: linux
+          env: MNE_STIM_CHANNEL=STI101
+               PYTHON_VERSION=3.7
+          language: python
+          python: "3.7"
+          addons:
+            apt:
+              packages:
+                - qt5-default  # Qt 5.12 release needs this to avoid a missing library bug
+        # Old dependencies
+        - os: linux
+          env: PYTHON_VERSION=3.5
+               CONDA_DEPENDENCIES="numpy=1.11 scipy=0.17 matplotlib=1.5 pandas=0.18 scikit-learn=0.18 pytest pytest-cov pytest-mock pytest-timeout"
+
+        # Minimal
+        - os: linux
+          env: DEPS=minimial
+               CONDA_DEPENDENCIES="numpy scipy matplotlib pytest pytest-cov pytest-mock pytest-timeout"
+               PIP_DEPENDENCIES="pytest-faulthandler pytest-sugar"
+
+# Setup anaconda
+before_install:
+    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
+        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;
+      fi;
+    - if [ -z "$CONDA_ENVIRONMENT" ] && [ -z "$CONDA_DEPENDENCIES" ]; then
+        pip uninstall -y numpy;
+        pip install -f "https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com" --pre numpy scipy;
+        pip install vtk;
+        pip install --upgrade -r requirements.txt;
+      else
+        git clone https://github.com/astropy/ci-helpers.git;
+        source ci-helpers/travis/setup_conda.sh;
+        if [ ! -z "$CONDA_ENVIRONMENT" ]; then
+          pip uninstall --yes mne;
+        fi;
+        if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
+          pip install --upgrade pyqt5>=5.10 pylsl;
+        else
+          conda install -c tstenner pylsl;
+        fi;
+      fi
+    # Don't source mne_setup_sh here because changing PATH etc. can't be done in a script
+    - if [ "${DEPS}" == "" ]; then
+        export MNE_ROOT="${PWD}/minimal_cmds";
+        export PATH=${MNE_ROOT}/bin:$PATH;
+        if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
+          curl https://staff.washington.edu/larsoner/minimal_cmds.tar.gz | tar xz;
+          export LD_LIBRARY_PATH=${MNE_ROOT}/lib:$LD_LIBRARY_PATH;
+          export NEUROMAG2FT_ROOT="${PWD}/minimal_cmds/bin";
+        else
+          curl https://staff.washington.edu/larsoner/minimal_cmds_osx.tar.gz | tar xz;
+          export DYLD_LIBRARY_PATH=${MNE_ROOT}/lib:$DYLD_LIBRARY_PATH;
+        fi;
+        mne_surf2bem --version;
+      fi;
 
 install:
-  # install miniconda
-  - deactivate
-  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
-  - MINICONDA_PATH=/home/travis/miniconda
-  - chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
-  - export PATH=$MINICONDA_PATH/bin:$PATH
-  - conda update --yes conda
-  # create the testing environment
-  - conda create -n testenv --yes python=$PYTHON_VERSION pip
-  - source activate testenv
-  - conda install --yes numpy==$NUMPY_VERSION scipy==$SCIPY_VERSION scikit-learn==$SKLEARN_VERSION nose pytest pytest-cov
-  - pip install codecov
-  - pip install .
+    # Rvm overrides cd with a function so that it can hook into it to run
+    # some scripts, see https://github.com/travis-ci/travis-ci/issues/8703
+    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
+        unset -f cd;
+      fi;
+    # Suppress the parallel outputs for logging cleanliness
+    - python setup.py build
+    - python setup.py install
+    - python -c "import mne_realtime; mne_realtime.__version__"
+
 
 script:
-  - mkdir for_test
-  - cd for_test
-  - pytest -v --cov=mne_realtime --pyargs mne_realtime
+    - echo "Print locale "
+    - locale
+    - echo "Other stuff"
+    - pytest -v --cov=mne_realtime --pyargs mne_realtime
 
-after_success:
-  - cp .coverage $TRAVIS_BUILD_DIR
-  - codecov --root $TRAVIS_BUILD_DIR || echo "codecov upload failed"
+after_script:
+    - cp .coverage $TRAVIS_BUILD_DIR
+    - codecov --root $TRAVIS_BUILD_DIR || echo "codecov upload failed"
